#!/usr/bin/env python3
"""
Schema exporter — generates a SCHEMA.md draft from your live semantic model.

Closes the gap the source project never did: its schema document claimed
"auto-generated" but no generator existed. This one queries the model's own
metadata through the SAME adapter your product uses (DAX INFO functions via
executeQueries), so it needs no extra tooling — if M05 passed, this works.

Usage:
    python scripts/export_model_schema.py > schema-draft.md

Then (Mission M06): review the draft, enrich descriptions (join keys, value
enumerations, warnings — the parts only a human knows), and replace
app/context_pack/SCHEMA.md with it.

Notes:
- INFO functions require a recent tabular model (compatibility level 1200+
  behind the executeQueries endpoint). If a query fails, the fallback route
  is Tabular Editor (export from the TOM tree) — see the mission text.
- The output deliberately contains NO workspace/dataset GUIDs and no data
  source connection expressions: identifiers stay in .env, and M expressions
  leaked real infrastructure paths in the source project's schema doc.
"""
from __future__ import annotations

import os
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv

load_dotenv()

from app.adapters.powerbi import (  # noqa: E402
    PowerBIAuthenticator,
    PowerBIClient,
    PowerBIError,
)


def _query(client: PowerBIClient, dataset_id: str, dax: str):
    result = client.execute_query(dataset_id, dax)
    return result.rows


def main() -> int:
    dataset_id = os.getenv("POWERBI_DATASET_ID", "").strip()
    if not dataset_id:
        print("POWERBI_DATASET_ID not set", file=sys.stderr)
        return 1

    try:
        client = PowerBIClient(PowerBIAuthenticator())

        tables = _query(client, dataset_id, "EVALUATE INFO.TABLES()")
        columns = _query(client, dataset_id, "EVALUATE INFO.COLUMNS()")
        measures = _query(client, dataset_id, "EVALUATE INFO.MEASURES()")
        try:
            relationships = _query(client, dataset_id, "EVALUATE INFO.RELATIONSHIPS()")
        except PowerBIError:
            relationships = []
    except PowerBIError as exc:
        print(f"Export failed: {exc}", file=sys.stderr)
        print(
            "If INFO functions are unavailable on your model, use the "
            "Tabular Editor route described in Mission M06.",
            file=sys.stderr,
        )
        return 1

    # Index metadata. INFO.* return implementation-named fields; be liberal.
    def field(row: dict, *names: str):
        for name in names:
            for key in row:
                if key.lower().replace("[", "").replace("]", "") == name.lower():
                    return row[key]
        return None

    table_names: dict = {}
    visible_tables = []
    for row in tables:
        tid = field(row, "ID")
        name = field(row, "Name")
        hidden = bool(field(row, "IsHidden"))
        if name and not str(name).startswith("DateTableTemplate"):
            table_names[tid] = name
            if not hidden:
                visible_tables.append((tid, name))

    cols_by_table = defaultdict(list)
    for row in columns:
        tid = field(row, "TableID")
        name = field(row, "ExplicitName", "Name", "InferredName")
        dtype = field(row, "ExplicitDataType", "DataType")
        hidden = bool(field(row, "IsHidden"))
        desc = field(row, "Description") or ""
        if name and str(name) != "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61":
            cols_by_table[tid].append((str(name), dtype, hidden, str(desc)))

    measures_by_table = defaultdict(list)
    for row in measures:
        tid = field(row, "TableID")
        name = field(row, "Name")
        expr = field(row, "Expression") or ""
        fmt = field(row, "FormatString") or ""
        hidden = bool(field(row, "IsHidden"))
        desc = field(row, "Description") or ""
        if name:
            measures_by_table[tid].append((str(name), str(expr).strip(), str(fmt), hidden, str(desc)))

    display_name = os.getenv("DATASET_DISPLAY_NAME", "Your Semantic Model")
    total_measures = sum(len(v) for v in measures_by_table.values())

    out = []
    out.append(f"# Semantic Model `{display_name}` — Schema Layer")
    out.append("")
    out.append(
        f"Generated by scripts/export_model_schema.py · {len(visible_tables)} visible "
        f"tables · {total_measures} measures · {len(relationships)} relationships"
    )
    out.append("")
    out.append(
        "> DRAFT: enrich every description with what only you know — join keys, "
        "value enumerations, traps. Descriptions ARE model behavior."
    )
    out.append("")

    for tid, name in visible_tables:
        out.append(f"## Table `{name}`")
        out.append("")
        out.append("| Column | Type | Hidden | Description |")
        out.append("|---|---|---|---|")
        for cname, dtype, hidden, desc in cols_by_table.get(tid, []):
            out.append(f"| `{cname}` | {dtype or ''} | {'yes' if hidden else 'no'} | {desc} |")
        out.append("")
        table_measures = measures_by_table.get(tid, [])
        if table_measures:
            out.append("### Measures")
            out.append("")
            for mname, expr, fmt, hidden, desc in table_measures:
                flag = " (hidden)" if hidden else ""
                out.append(f"- **{mname}**{flag}: `{expr}`" + (f" · format `{fmt}`" if fmt else "") + (f" — {desc}" if desc else ""))
            out.append("")

    if relationships:
        out.append("## Relationships")
        out.append("")
        out.append("| From table | From column | To table | To column | Active |")
        out.append("|---|---|---|---|---|")
        for row in relationships:
            from_t = table_names.get(field(row, "FromTableID"), "?")
            to_t = table_names.get(field(row, "ToTableID"), "?")
            from_c = field(row, "FromColumn", "FromColumnID") or "?"
            to_c = field(row, "ToColumn", "ToColumnID") or "?"
            active = "yes" if field(row, "IsActive") else "no"
            out.append(f"| `{from_t}` | {from_c} | `{to_t}` | {to_c} | {active} |")
        out.append("")

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
